version: '3.9'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.backend
    ports:
      - '5000:5000'
    environment:
      NODE_ENV: production
      MONGO_URI_PROD: ${MONGO_URI_PROD}
      JWT_SECRET: ${JWT_SECRET}
      TOGETHER_API_KEY: ${TOGETHER_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./server/uploads:/app/uploads
    networks:
      - app_network
    restart: always

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.frontend
    networks:
      - app_network
    restart: always

  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - frontend
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
